### ISSUE TITLE
minified source-less (non-free) javascript

### ISSUE THREAD

**Issue by onlyjob** [michaelfranzl/SalorHospitality#14]
[vendor/assets/javascripts/jquery.modcoder.excolor.js](../blob/master/salor-hospitality/vendor/assets/javascripts/jquery.modcoder.excolor.js) is minified source-less file.
Minified javascripts are effectively the same as pre-compiled binaries --
un-readable, non-modifiable and non-distributable in
[Debian](http://debian.org). It is the best to have no minified files in source tree at all.

Moreover ExColor seems to be dead upstream and according to [last web site snapshot](https://web.archive.org/web/20130317111944/http://modcoder.org/?ptab=jquery&item=excolor)
upstream distributed ExColor in minified form without source code.

Please consider removing obsolete `jquery.modcoder.excolor.js` and replacing it with non-minified up-to-date alternative like

 * https://github.com/wieringen/tinycolorpicker
 * https://github.com/josedvq/colpick-jQuery-Color-Picker
 * https://github.com/mjolnic/bootstrap-colorpicker

or others. Thanks.

**Comment by michaelfranzl** [comment]
Thanks for the heads-up. It makes sense to replace this color picker with one of the alternatives you provided. I'll integrate it in the following few days.

**Comment by michaelfranzl** [comment]
Replaced with https://github.com/josedvq/colpick-jQuery-Color-Picker in `jessie` and `master` branch.

**Comment by onlyjob** [comment]
Awesome. Thank you. :)
